services:
  nvim:
    build: .
    image: docker-nvim
    container_name: docker-nvim
    stdin_open: true
    tty: true
    volumes:
      - . :/workspace
    working_dir: /workspace
    environment:
      - TERM=xterm-256color
